import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/styles/globals.scss';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
			<body>{children}</body>
		</html>
	);
}



// src/
// ├── app/              # rutas (Next)
// ├── components/       # UI reutilizable
// ├── sections/         # bloques de la página (Hero, RSVP...)
// ├── hooks/            # custom hooks
// ├── lib/              # utilidades
// ├── types/            # tipos TS
// ├── styles/           # scss global (variables, mixins)
// └── assets/           # imágenes, fuentes locales


// requerido:
// GSAP + Spline
// Framer Motion